### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by janpapenbrock** [codeformuenster/parkleitsystem-api#14]
Die API ist down - http://parkleit-api.codeformuenster.org/

```
~> curl http://parkleit-api.codeformuenster.org/
default backend - 404
```

```
~> curl -I http://parkleit-api.codeformuenster.org/
HTTP/1.1 404 Not Found
Server: nginx/1.11.3
Date: Mon, 16 Jan 2017 21:10:25 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; preload
```

Dementsprechend zeigt die Visualisierung auch nichts mehr an: http://codeformuenster.org/carparcsmuenster/#/?_k=in26jr

**Comment by webwurst** [comment]
Besten Dank! Schau ich mir heute Abend mal an :)

**Comment by webwurst** [comment]
Api tut wieder, aber das Format hat sich vermutlich geändert.
Siehe: https://github.com/codeformuenster/carparcsmuenster/issues/1
